echo "=== SITEMAP PROOF ==="
curl -sI https://www.kassia.ro/sitemap.xml | grep -iE "^HTTP|^location|^content-type"
echo "---"
curl -sI https://www.kassia.ro/sitemap.xml/ | grep -iE "^HTTP|^location|^content-type"
echo "---"
curl -sI https://www.kassia.ro/sitemap_index.xml | grep -iE "^HTTP|^location|^content-type"
echo "---"
curl -sI https://www.kassia.ro/sitemap_index.xml/ | grep -iE "^HTTP|^location|^content-type"
echo "---"
curl -sI https://www.kassia.ro/sitemap-index.xml | grep -iE "^HTTP|^location|^content-type"
echo "---"
curl -sI https://www.kassia.ro/sitemap-index.xml/ | grep -iE "^HTTP|^location|^content-type"
echo "---"
curl -sI https://www.kassia.ro/robots.txt | grep -iE "^HTTP|^location|^content-type"
